version: "3"

services:

  my-kind-demo-webapp:
    image: simple-microservice-webapp:latest
    pull_policy: if_not_present
    depends_on:
      - my-kind-demo-service    
    ports:
      - 8080:8080
    environment:
      backend.url: "http://my-kind-demo-service:8081"      

  my-kind-demo-service:
    image: simple-microservice-backend:latest
    pull_policy: if_not_present
    ports:
      - 8081:8081

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16

