version: "3"

services:

  my-kind-demo-webapp:
    image: my-kind-demo-webapp-image:latest
    pull_policy: if_not_present
    container_name: my-kind-demo-webapp
    depends_on:
      - my-kind-demo-service    
    ports:
      - 8080:8080
    environment:
      kinddemo.service.host: "my-kind-demo-service"      

  my-kind-demo-service:
    image: my-kind-demo-service-image:latest
    pull_policy: if_not_present    
    ports:
      - 8081:8081

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16

